//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Hccs.WebApp
{
    using System;
    using System.Collections.Generic;
    
    public partial class Course
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Course()
        {
            this.Schedules = new HashSet<Schedule>();
        }
    
        public string CourseID { get; set; }
        public string CourseNameEnglish { get; set; }
        public string CourseNameChinese { get; set; }
        public short CourseType { get; set; }
        public Nullable<decimal> RegistrationFee { get; set; }
        public Nullable<decimal> Tuition { get; set; }
        public string Schoolyear { get; set; }
        public string Semester { get; set; }
        public string Description { get; set; }
        public Nullable<int> PreferredSeqNum { get; set; }
        public Nullable<short> NumOfUnits { get; set; }
        public Nullable<int> Minimumage { get; set; }
        public System.DateTime Created { get; set; }
        public int CreatedByID { get; set; }
        public Nullable<System.DateTime> Updated { get; set; }
        public Nullable<int> UpdatedByID { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Schedule> Schedules { get; set; }
    }
}
