//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Hccs.WebApp
{
    using System;
    using System.Collections.Generic;
    
    public partial class h_Account
    {
        public int h_Account_id { get; set; }
        public int AccountID { get; set; }
        public int PersonID { get; set; }
        public Nullable<System.DateTime> AccountConfirmedDt { get; set; }
        public short AccountStatus { get; set; }
        public string Username { get; set; }
        public string Password { get; set; }
        public string ConfirmationCode { get; set; }
        public System.DateTime Created { get; set; }
        public int CreatedByID { get; set; }
        public Nullable<System.DateTime> Updated { get; set; }
        public Nullable<int> UpdatedByID { get; set; }
        public System.DateTime h_created_date { get; set; }
        public string h_action_flag { get; set; }
        public int h_user_id { get; set; }
    }
}
