//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Hccs.WebApp
{
    using System;
    using System.Collections.Generic;
    
    public partial class h_Hccsrole
    {
        public int h_Hccsrole_id { get; set; }
        public int HCCSRoleID { get; set; }
        public int PersonID { get; set; }
        public short HccsRole { get; set; }
        public string Schoolyear { get; set; }
        public string Semester { get; set; }
        public string HccsTitleEnglish { get; set; }
        public string HccsTitleChinese { get; set; }
        public System.DateTime Created { get; set; }
        public int CreatedByID { get; set; }
        public Nullable<System.DateTime> Updated { get; set; }
        public Nullable<int> UpdatedByID { get; set; }
        public System.DateTime h_created_date { get; set; }
        public string h_action_flag { get; set; }
        public int h_user_id { get; set; }
    }
}
