//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Hccs.WebApp
{
    using System;
    using System.Collections.Generic;
    
    public partial class h_Payment
    {
        public int h_Payment_id { get; set; }
        public int PaymentUID { get; set; }
        public int PaymentID { get; set; }
        public int AccountID { get; set; }
        public Nullable<int> ObligationID { get; set; }
        public string PaymentMethod { get; set; }
        public string Checknum { get; set; }
        public decimal Amount { get; set; }
        public string Note { get; set; }
        public Nullable<System.DateTime> ReceiveDate { get; set; }
        public Nullable<System.DateTime> ProcessedDate { get; set; }
        public string Processed { get; set; }
        public string Confirmed { get; set; }
        public Nullable<System.DateTime> ConfirmedDate { get; set; }
        public Nullable<int> ConfirmedByID { get; set; }
        public Nullable<int> CampusID { get; set; }
        public System.DateTime Created { get; set; }
        public int CreatedByID { get; set; }
        public Nullable<System.DateTime> Updated { get; set; }
        public Nullable<int> UpdatedByID { get; set; }
        public System.DateTime h_created_date { get; set; }
        public string h_action_flag { get; set; }
        public int h_user_id { get; set; }
    }
}
