//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Hccs.WebApp
{
    using System;
    using System.Collections.Generic;
    
    public partial class h_Schedule
    {
        public int h_Schedule_id { get; set; }
        public int ScheduleID { get; set; }
        public string CourseID { get; set; }
        public string ClassroomID { get; set; }
        public int HccsRoleID { get; set; }
        public Nullable<int> TextbookID { get; set; }
        public int SchoolYear { get; set; }
        public string Semester { get; set; }
        public string ClassNameEnglish { get; set; }
        public string ClassNameChinese { get; set; }
        public Nullable<int> Capacity { get; set; }
        public string ClassTime { get; set; }
        public Nullable<decimal> Classstarttime { get; set; }
        public Nullable<decimal> Classendtime { get; set; }
        public int WaitinglistLimit { get; set; }
        public System.DateTime Created { get; set; }
        public int CreatedByID { get; set; }
        public Nullable<System.DateTime> Updated { get; set; }
        public Nullable<int> UpdatedByID { get; set; }
        public System.DateTime h_created_date { get; set; }
        public string h_action_flag { get; set; }
        public int h_user_id { get; set; }
    }
}
