//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Hccs.WebApp
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class HccsWebDBEntities : DbContext
    {
        public HccsWebDBEntities()
            : base("name=HccsWebDBEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Account> Accounts { get; set; }
        public virtual DbSet<Campus> Campus1 { get; set; }
        public virtual DbSet<Classroom> Classrooms { get; set; }
        public virtual DbSet<Course> Courses { get; set; }
        public virtual DbSet<Enrollment> Enrollments { get; set; }
        public virtual DbSet<Hccsrole> Hccsroles { get; set; }
        public virtual DbSet<Invoice> Invoices { get; set; }
        public virtual DbSet<Payment> Payments { get; set; }
        public virtual DbSet<Person> People { get; set; }
        public virtual DbSet<Refund> Refunds { get; set; }
        public virtual DbSet<Schedule> Schedules { get; set; }
        public virtual DbSet<Textbook> Textbooks { get; set; }
        public virtual DbSet<Deadline> Deadlines { get; set; }
        public virtual DbSet<h_Account> h_Account { get; set; }
        public virtual DbSet<h_Enrollment> h_Enrollment { get; set; }
        public virtual DbSet<h_Hccsrole> h_Hccsrole { get; set; }
        public virtual DbSet<h_Invoice> h_Invoice { get; set; }
        public virtual DbSet<h_Payment> h_Payment { get; set; }
        public virtual DbSet<h_Person> h_Person { get; set; }
        public virtual DbSet<h_Refund> h_Refund { get; set; }
        public virtual DbSet<h_Schedule> h_Schedule { get; set; }
    }
}
