//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Hccs.WebApp
{
    using System;
    using System.Collections.Generic;
    
    public partial class Refund
    {
        public int RefundID { get; set; }
        public int AccountID { get; set; }
        public string Checknum { get; set; }
        public decimal Amount { get; set; }
        public string Note { get; set; }
        public System.DateTime ProcessedDate { get; set; }
        public string Processed { get; set; }
        public System.DateTime Created { get; set; }
        public int CreatedByID { get; set; }
        public Nullable<System.DateTime> Updated { get; set; }
        public Nullable<int> UpdatedByID { get; set; }
    
        public virtual Account Account { get; set; }
    }
}
