//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Hccs.WebApp
{
    using System;
    using System.Collections.Generic;
    
    public partial class Schedule
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Schedule()
        {
            this.Enrollments = new HashSet<Enrollment>();
        }
    
        public int ScheduleID { get; set; }
        public string CourseID { get; set; }
        public string ClassroomID { get; set; }
        public int HccsRoleID { get; set; }
        public Nullable<int> TextbookID { get; set; }
        public int SchoolYear { get; set; }
        public string Semester { get; set; }
        public string ClassNameEnglish { get; set; }
        public string ClassNameChinese { get; set; }
        public Nullable<int> Capacity { get; set; }
        public string ClassTime { get; set; }
        public Nullable<decimal> Classstarttime { get; set; }
        public Nullable<decimal> Classendtime { get; set; }
        public int WaitinglistLimit { get; set; }
        public System.DateTime Created { get; set; }
        public int CreatedByID { get; set; }
        public Nullable<System.DateTime> Updated { get; set; }
        public Nullable<int> UpdatedByID { get; set; }
    
        public virtual Classroom Classroom { get; set; }
        public virtual Course Course { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Enrollment> Enrollments { get; set; }
        public virtual Hccsrole Hccsrole { get; set; }
        public virtual Textbook Textbook { get; set; }
    }
}
